# Generated by Django 5.1.5 on 2025-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='urlchars',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='1', max_length=100, unique=True),
        ),
    ]
